/* Total number of patients in the hospital? */
SELECT * FROM total_patients;

/* Total number of doctors working in the hospital? */
SELECT * FROM total_doctors;

/* Total number of appointments scheduled? */
SELECT * FROM scheduled_appointments;

/* Total revenue generated from billing? */
SELECT * FROM total_revenue;

/* Total completed appointments and cancelled appointments? */
SELECT * FROM completed_cancelled_appointments;

/* Which doctor handled the highest number of appointments? */
SELECT * FROM top_doctor_by_appointments;

/* How many appointments were handled by each specialization? */
SELECT * FROM specialization_appointments;

/* Which hospital branch has the most doctors? */
SELECT * FROM top_hospital_branch;

/* Which treatment type was performed most frequently? */
SELECT * FROM most_frequent_treatment;

/* What is the total revenue generated by each treatment type? */
SELECT * FROM treatment_revenue;

/* What is the average treatment cost by treatment type? */
SELECT * FROM avg_treatment_cost;

/* Which insurance provider covers the highest number of patients? */
SELECT * FROM top_insurance_provider;

/* Which payment method is used most frequently? */
SELECT * FROM top_payment_method;

/* Rank doctors based on the number of appointments handled. */
SELECT * FROM doctor_rankings;

/* Rank treatment types based on the revenue generated. */
SELECT * FROM treatment_rankings;

/* Find the top 5 revenue-generating doctors. */
SELECT * FROM top_5_revenue_doctors;

/* Find patients who visited the hospital more than once. */
SELECT * FROM repeat_patients;

/* Find the top 10 patients based on total billing amount. */
SELECT * FROM top_10_patients_billing;

/* Calculate each specialization's contribution to total revenue. */
SELECT * FROM specialization_revenue_contribution;

/* Calculate monthly revenue trends */
SELECT * FROM monthly_revenue_trend;

SHOW FULL TABLES
WHERE TABLE_TYPE = 'VIEW';

DROP VIEW IF EXISTS total_patients,
                    total_doctors,
                    scheduled_appointments,
                    total_revenue,
                    appointment_status_summary,
                    doctor_highest_appointments,
                    specialization_appointments,
                    top_payment_method,
                    avg_treatment_cost,
                    top_hospital_branch,
                    top_doctor_by_appointments,
                    completed_cancelled_appointments,
                    branch_most_doctors,
                    most_frequent_treatment,
                    treatment_revenue,
                    average_treatment_cost,
                    top_insurance_provider,
                    payment_method_usage,
                    doctor_rankings,
                    top_10_patients_billing ,
                    top_5_revenue_doctors,
                    treatment_rankings,
                    top_revenue_doctors,
                    repeat_patients,
                    top_billing_patients,
                    specialization_revenue_contribution,
                    monthly_revenue_trend;