/* Total number of patients in the hospital? */
CREATE VIEW total_patients AS
SELECT COUNT(patient_id) AS total_patients
FROM patients4;


/* Total number of doctors working in the hospital? */
CREATE VIEW total_doctors AS
SELECT COUNT(doctor_id) AS total_doctors
FROM doctors3;


/* Total appointments scheduled? */
CREATE VIEW scheduled_appointments AS
SELECT COUNT(*) AS total_scheduled_appointments
FROM appointments1
WHERE status = 'Scheduled';


/* Total revenue generated from billing? */
CREATE VIEW total_revenue AS
SELECT SUM(amount) AS total_revenue
FROM billing2;


/* Total completed appointments and cancelled appointments? */
CREATE VIEW completed_cancelled_appointments AS
SELECT status,
       COUNT(*) AS total_appointments
FROM appointments1
WHERE status IN ('Completed', 'Cancelled')
GROUP BY status;


/* Which doctor handled the highest number of appointments? */
CREATE VIEW top_doctor_by_appointments AS
SELECT d.doctor_id,
       COUNT(a.appointment_id) AS total_appointments
FROM doctors3 d
INNER JOIN appointments1 a
        ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id
ORDER BY total_appointments DESC
LIMIT 1;


/* How many appointments were handled by each specialization? */
CREATE VIEW specialization_appointments AS
SELECT d.specialization,
       COUNT(a.appointment_id) AS total_appointments
FROM appointments1 a
INNER JOIN doctors3 d
        ON a.doctor_id = d.doctor_id
GROUP BY d.specialization;


/* Which hospital branch has the most doctors? */
CREATE VIEW top_hospital_branch AS
SELECT hospital_branch,
       COUNT(doctor_id) AS doctor_count
FROM doctors3
GROUP BY hospital_branch
ORDER BY doctor_count DESC
LIMIT 1;


/* Which treatment type was performed most frequently? */
CREATE VIEW most_frequent_treatment AS
SELECT treatment_type,
       COUNT(treatment_type) AS treatment_frequency
FROM treatments5
GROUP BY treatment_type
ORDER BY treatment_frequency DESC
LIMIT 1;


/* What is the total revenue generated by each treatment type? */
CREATE VIEW treatment_revenue AS
SELECT treatment_type,
       SUM(cost) AS total_revenue
FROM treatments5
GROUP BY treatment_type;


/* What is the average treatment cost by treatment type? */
CREATE VIEW avg_treatment_cost AS
SELECT treatment_type,
       ROUND(AVG(cost),0) AS average_treatment_cost
FROM treatments5
GROUP BY treatment_type;


/* Which insurance provider covers the highest number of patients? */
CREATE VIEW top_insurance_provider AS
SELECT insurance_provider,
       COUNT(patient_id) AS patient_count
FROM patients4
GROUP BY insurance_provider
ORDER BY patient_count DESC
LIMIT 1;


/* Which payment method is used most frequently? */
CREATE VIEW top_payment_method AS
SELECT payment_method,
       COUNT(*) AS usage_count
FROM billing2
GROUP BY payment_method
ORDER BY usage_count DESC
LIMIT 1;


/* Rank doctors based on number of appointments handled */
CREATE VIEW doctor_rankings AS
SELECT d.doctor_id,
       d.first_name,
       d.last_name,
       COUNT(*) AS total_appointments,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS doctor_rank
FROM doctors3 d
INNER JOIN appointments1 a
        ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id,
         d.first_name,
         d.last_name;


/* Rank treatment types based on revenue generated */
CREATE VIEW treatment_rankings AS
SELECT treatment_type,
       ROUND(SUM(cost),0) AS total_revenue,
       RANK() OVER (ORDER BY SUM(cost) DESC) AS treatment_rank
FROM treatments5
GROUP BY treatment_type;


/* Find the top 5 revenue-generating doctors */
CREATE VIEW top_5_revenue_doctors AS
SELECT d.doctor_id,
       d.first_name,
       d.last_name,
       ROUND(SUM(t.cost),0) AS total_revenue
FROM doctors3 d
INNER JOIN appointments1 a
        ON d.doctor_id = a.doctor_id
INNER JOIN treatments5 t
        ON a.appointment_id = t.appointment_id
GROUP BY d.doctor_id,
         d.first_name,
         d.last_name
ORDER BY total_revenue DESC
LIMIT 5;


/* Find patients who visited more than once */
CREATE VIEW repeat_patients AS
SELECT patient_id,
       COUNT(*) AS visit_count
FROM appointments1
GROUP BY patient_id
HAVING COUNT(*) > 1;


/* Find the top 10 patients by billing amount along with their names */
CREATE VIEW top_10_patients_billing AS
SELECT b.patient_id,
       p.first_name,
       p.last_name,
       ROUND(SUM(b.amount),0) AS total_revenue
FROM billing2 b
INNER JOIN patients4 p
        ON b.patient_id = p.patient_id
GROUP BY b.patient_id,
         p.first_name,
         p.last_name
ORDER BY total_revenue DESC
LIMIT 10;


/* Calculate each specialization's contribution to total revenue */
CREATE VIEW specialization_revenue_contribution AS
SELECT d.specialization,
       ROUND(SUM(b.amount),0) AS total_revenue,
       ROUND(
           SUM(b.amount) * 100.0 /
           SUM(SUM(b.amount)) OVER (),
           2
       ) AS contribution_percentage
FROM doctors3 d
INNER JOIN appointments1 a
        ON d.doctor_id = a.doctor_id
INNER JOIN treatments5 t
        ON a.appointment_id = t.appointment_id
INNER JOIN billing2 b
        ON t.treatment_id = b.treatment_id
GROUP BY d.specialization;


/* Calculate monthly revenue trends */
CREATE VIEW monthly_revenue_trend AS
SELECT YEAR(bill_date) AS revenue_year,
       MONTH(bill_date) AS revenue_month,
       ROUND(SUM(amount),0) AS total_revenue
FROM billing2
GROUP BY YEAR(bill_date),
         MONTH(bill_date)
ORDER BY YEAR(bill_date),
         MONTH(bill_date);